on:
  push:
    branches:
      - master
      - release-please**
  release:
    types: [created]

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.GITHUB_TOKEN }}
  notify-teams:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.release.created == true
    steps:
      # - name: Microsoft Teams Notification
      #   uses: skitionek/notify-microsoft-teams@master
      #   with:
      #     webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
      #     overwrite: "{title: `New Release: ${github.event.release.name}`}"
      - run: |
          echo "Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"